name: COBOL Check Automation

on:
  push:
    branches: [main]

jobs:
  cobol-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm i -g @zowe/cli
      - name: Setup Mainframe Environment and Upload COBOL Check
        env:
          ZOWE_OPT_USER: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_OPT_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
          Z_HOST: ${{ secrets.Z_HOST }}
          Z_PORT: ${{ secrets.Z_PORT }}
        run: |
          chmod +x .github/scripts/zowe_operations.sh
          .github/scripts/zowe_operations.sh
      - name: Run COBOL Check on Mainframe
        env:
          ZOWE_OPT_USER: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_OPT_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
          Z_HOST: ${{ secrets.Z_HOST }}
          Z_PORT: ${{ secrets.Z_PORT }}
        run: |
          chmod +x .github/scripts/mainframe_operations.sh
          .github/scripts/mainframe_operations.sh
