name: COBOL Check Automation

on:
  push:
    branches: [main]

jobs:
  cobol-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm i -g @zowe/cli
      - name: Setup Mainframe Environment and Upload COBOL Check
        env:
          ZOWE_OPT_USER: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_OPT_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
          ZOWE_OPT_HOST: ${{ secrets.Z_HOST }}
          ZOWE_OPT_PORT: ${{ secrets.Z_PORT }}
          ZOWE_OPT_REJECT_UNAUTHORIZED: false
        run: |
          chmod +x .github/scripts/zowe_operations.sh
          .github/scripts/zowe_operations.sh
      - name: Run COBOL Check on Mainframe
        env:
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
          ZOWE_HOST: ${{ secrets.Z_HOST }}
        run: |
          sshpass -p "$ZOWE_PASSWORD" ssh -o StrictHostKeyChecking=no $ZOWE_USERNAME@$ZOWE_HOST 'sh -s' < sed -e 's/ZOWE_USERNAME=/ZOWE_USERNAME=$ZOWE_USERNAME/' .github/scripts/mainframe_operations.sh
